apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-basic-auth-%s" (include "chart.basename" .) .Release.Name | trunc 63 | trimSuffix "-" }}
type: Opaque
data:
  auth: {{ printf "%s:%s\n" .Values.app.auth.username .Values.app.auth.password | b64enc }}
