apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc-%s" (include "chart.basename" .) .Release.Name | trunc 63 | trimSuffix "-" }}
spec:
  selector:
    app: {{ include "chart.fullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ if .Values.app.auth.enabled }}8080{{ else }}{{ .Values.app.port }}{{ end }}
